//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dragonchau.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicineUnit
    {
        public int MedicineID { get; set; }
        public int UnitID { get; set; }
        public int UnitConvert { get; set; }
        public string UnitName { get; set; }
    
        public virtual Medicine Medicine { get; set; }
        public virtual Unit Unit { get; set; }
    }
}
