//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dragonchau.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations.Schema;
    
    public partial class Medicine
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Medicine()
        {
            this.BillDetails = new HashSet<BillDetail>();
            this.MedicineUnits = new HashSet<MedicineUnit>();
        }
    
        public int MedicineID { get; set; }
        [DisplayName("Tên thuốc")]
        public string MedicineName { get; set; }
        [DisplayName("Giá nhập")]
        public Nullable<decimal> MedicinePrice { get; set; }
        [DisplayName("Hãng")]
        public Nullable<int> MedicineBrand { get; set; }
        [DisplayName("Hình ảnh")]
        public byte[] MedicineImg { get; set; }
        [DisplayName("Hạn sử dụng")]
        public Nullable<System.DateTime> MedicineExp { get; set; }
        [DisplayName("Mô tả")]
        public string MedicineDescription { get; set; }
        [DisplayName("Thành phần")]
        public string MedicineIngredients { get; set; }
        [DisplayName("Tồn kho")]
        public Nullable<int> Available { get; set; }
        [DisplayName("Đơn vị cơ bản")]
        public Nullable<int> BaseUnit { get; set; }
        [DisplayName("Giá bán")]
        public Nullable<decimal> MedicinePrice_Sell { get; set; }
        [DisplayName("Nhóm thuốc")]
        public Nullable<int> MedicineCate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BillDetail> BillDetails { get; set; }
        public virtual Brand Brand { get; set; }
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MedicineUnit> MedicineUnits { get; set; }
    }
}
