//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dragonchau.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations.Schema;
    
    public partial class Medicine
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Medicine()
        {
            this.BillDetails = new HashSet<BillDetail>();
            this.MedicineUnits = new HashSet<MedicineUnit>();
        }
    
        public int MedicineID { get; set; }
        [DisplayName("Tên thuốc")]
        [Required(ErrorMessage = "Mẹ m béo")]
        public string MedicineName { get; set; }
        public Nullable<decimal> MedicinePrice { get; set; }
        public Nullable<int> MedicineBrand { get; set; }
        public byte[] MedicineImg { get; set; }
        public Nullable<System.DateTime> MedicineExp { get; set; }
        public string MedicineDescription { get; set; }
        public string MedicineIngredients { get; set; }
        public Nullable<int> Available { get; set; }
        public Nullable<int> BaseUnit { get; set; }
        public Nullable<decimal> MedicinePrice_Sell { get; set; }
        public Nullable<int> MedicineCate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BillDetail> BillDetails { get; set; }
        public virtual Brand Brand { get; set; }
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MedicineUnit> MedicineUnits { get; set; }
    }
}
