//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dragonchau.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations.Schema;
    
    public partial class Staff
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Staff()
        {
            this.Bills = new HashSet<Bill>();
        }
    
        public int StaffID { get; set; }

        [DisplayName("Tên nhân viên")]
        [Required(ErrorMessage = "Chưa nhập tên nhân viên")]
        public string StaffName { get; set; }
        [DisplayName("Số điện thoại")]
        [Required(ErrorMessage = "Chưa nhập số điện thoại")]
        public string StaffPhone { get; set; }
        public string StaffEmail { get; set; }
        [DisplayName("Lương nhân viên")]
        public Nullable<int> StaffSalary { get; set; }
        public string StaffIDnum { get; set; }
        public Nullable<System.DateTime> StaffDateCreate { get; set; }
        public Nullable<int> StaffRole { get; set; }
    
        public virtual Account Account { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bill> Bills { get; set; }
        public virtual Role Role { get; set; }
    }
}
